export const hawkerCentres = [
  [
    "Ci Yuan Hawker Centre",
    "West Coast Drive Blk 502 (Ayer Rajah Market)",
    "West Coast Drive Blk 503 (Ayer Rajah Food Centre)",
    "Bedok South Road Blk 16",
    "Pasir Ris Central Hawker Centre",
    "Tampines Street 11 Blk 137 (Tampines Round Market and Food Centre)",
    "Toa Payoh Lorong 5 Blk 75",
    "Zion Riverside Food Centre",
    "Woodleigh Village Hawker Centre",
    "Tiong Bahru Market",
    "Toa Payoh Lorong 1 Blk 127 (Toa Payoh West Market and Food Court)",
    "Bukit Canberra Hawker Centre",
    "Anchorvale Village Hawker Centre",
    "Fernvale Hawker Centre",
    "Punggol Town Hub Hawker Centre",
    "Tanjong Pagar Plaza Blk 6 (Blk 6 Tanjong Pagar Plaza Market and Food Centre)",
    "Ang Mo Kio Street 22 Blk 226H (Kebun Baru Food Centre)",
    "Bedok Food Centre",
    "Bedok North Street 1 Blk 216",
    "Bedok North Street 3 Blk 511 (Kaki Bukit 511 Market and Food Centre)",
    "Bedok North Street 3 Blk 538",
    "Bedok North Street 4 Blk 85 (85 Fengshan Centre)",
    "Bedok Reservoir Road Blk 630",
    "Circuit Road Blk 89",
    "Holland Drive Blk 44 (Holland Drive Market and Food Centre)",
    "Toa Payoh Lorong 4 Blk 93",
    "Toa Payoh Lorong 7 Blk 22 (Kim Keat Palm Market and Food Centre)",
    "Toa Payoh Lorong 8 Blk 210",
    "Upper Boon Keng Road Blk 17 (Blk 17 Upper Boon Keng Market and Food Centre)",
    "Upper Cross Street Blk 531A (Hong Lim Food Centre and Market)",
    "East Coast Lagoon Food Village",
    "Circuit Road Blk 79/79A",
    "Jurong West Street 52 Blk 505",
    "North Bridge Road Market",
    "Bukit Merah View Blk 115 (Blk 115 Bukit Merah View Market and Food Centre)",
    "Newton Food Centre",
    "Yishun Park Hawker Centre",
    "Yishun Ring Road Blk 104/105 (Chong Pang Market and Food Centre)",
    "Ang Mo Kio Ave 1 Blk 341 (Teck Ghee Court)",
    "Ang Mo Kio Ave 10 Blk 453A (Chong Boon Market and Food Centre)",
    "Ang Mo Kio Ave 6 Blk 724 (Blk 724 Ang Mo Kio Market)",
    "Clementi Ave 3 Blk 448",
    "Taman Jurong Market and Food Centre",
    "New Market Road Blk 32 (People's Park Food Centre)",
    "Clementi Ave 2 Blk 353 (Clementi Ave 2 Market/Cooked Food Centre)",
    "New Upper Changi Road Blk 208B",
    "New Upper Changi Road Blk 58",
    "Old Airport Road Blk 51 (51 Old Airport Road Food Centre and Shopping Mall)",
    "Clementi West Street 2 Blk 726",
    "Commonwealth Drive Blk 1A/2A/3A (Tanglin Halt Food Centre/Commonwealth Drive Food Centre)",
    "Eunos Crescent Blk 4A",
    "Bukit Panjang Hawker Centre",
    "Bukit Timah Market",
    "Chomp Chomp Food Centre",
    "Mei Chin Road Blk 159 (Mei Chin Road Market)",
    "Pasir Panjang Food Centre",
    "Redhill Lane Blk 79 (Redhill Market)",
    "Redhill Lane Blk 85 (Redhill Food Centre)",
    "Serangoon Garden Market",
    "Shunfu Road Blk 320 (Shunfu Mart)",
    "Geylang Bahru Blk 69 (Blk 69 Geylang Bahru Market and Food Centre)",
    "Ghim Moh Road Blk 20",
    "Smith Street Blk 335 (Chinatown Complex Market)",
    "Tanglin Halt Market",
    "Jalan Kukoh Blk 1 (Kukoh 21 Food Centre)",
    "Jurong East Ave 1 Blk 347 (Yuhua Market and Hawker Centre)",
    "Jurong East Street 24 Blk 254 (Yuhua Village Market and Food Centre)",
    "Kallang Estate Fresh Market and Food Centre",
    "Holland Village Market and Food Centre",
    "Hougang Ave 1 Blk 105 (Hougang 105 Hainanese Village Centre)",
    "Hougang Street 21 Blk 209 (Kovan Hougang Market and Food Centre)",
    "Jalan Bukit Merah Blk 112 (Blk 112 Jalan Bukit Merah Market and Food Centre)",
    "Jalan Bukit Merah Blk 6 (ABC Brickworks Market/Food Centre)",
    "Maxwell Food Centre (Kim Hua Market)",
    "Commonwealth Crescent Market",
    "Empress Road Blk 7 (Empress Road Market and Food Centre)",
    "Boon Lay Place Blk 221A/B (Boon Lay Place Market and Food Village)",
    "Geylang Serai Market",
    "Jurong West Hawker Centre",
    "kml_79",
    "Bukit Merah Central Blk 163 (Bukit Merah Central Food Centre)",
    "Cambridge Road Blk 41A (Pek Kio Market and Food Centre)",
    "Changi Village Blk 2 and 3",
    "Circuit Road Blk 80 (80 Circuit Road Market and Food Centre)",
    "Dunman Food Centre",
    "Haig Road Blk 13/14 (Haig Road Market and Cooked Food Centre)",
    "Havelock Road Blk 22A/B (Havelock Road Cooked Food Centre)",
    "Whampoa Drive Blk 91/92 (Whampoa Drive Makan Place/Whampoa Market)",
    "Kampung Admiralty Hawker Centre",
    "Marine Parade Central Blk 84 (84 Marine Parade Central Market and Food Centre)",
    "Adam Road Food Centre",
    "Aljunied Ave 2 Blk 117 (Blk 117 Aljunied Market and Food Centre)",
    "Amoy Street Food Centre (Telok Ayer Food Centre)",
    "Sims Place Blk 49 (Sims Vista Market and Food Centre)",
    "Golden Mile Food Centre",
    "Jalan Batu Blk 4A (Blk 4A Jalan Batu Hawker Centre/Market)",
    "Bendemeer Road Blk 29 (Bendemeer Market and Food Centre)",
    "Beo Crescent Market",
    "Berseh Food Centre",
    "Buffalo Road Blk 665 (Tekka Centre/Zhu Jiao Market)",
  ],
];
